<a href="https://colab.research.google.com/github/fattahsamit/ml/blob/main/ML_Basics/NumPy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy

In [3]:
import numpy as np

In [6]:
python_list = [1, 2, 3, 4, 5]

arr = np.array(python_list)
arr

array([1, 2, 3, 4, 5])

In [10]:
python_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

arr = np.array(python_list)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
arr = np.arange(0, 10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])