<a href="https://colab.research.google.com/github/fattahsamit/ml/blob/main/ML_Basics/NumPy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [90]:
!pip install numpy

In [91]:
import numpy as np

In [92]:
python_list = [1, 2, 3, 4, 5]

arr = np.array(python_list)
arr

array([1, 2, 3, 4, 5])

In [93]:
python_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

arr = np.array(python_list)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [94]:
arr = np.arange(0, 10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [95]:
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])

In [96]:
print(np.zeros(5))
print("\n")

np.zeros((4,3), dtype=int)

[0. 0. 0. 0. 0.]




array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [97]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [98]:
np.ones((4,3,5), dtype=int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [99]:
np.full((4,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [100]:
# Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [101]:
np.linspace(-1,1,5)

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [102]:
np.logspace(0,10,7, base=np.e)

# np.logspace(0,10,7)

# np.logspace(0,10,7, base=2)

array([1.00000000e+00, 5.29449005e+00, 2.80316249e+01, 1.48413159e+02,
       7.85771994e+02, 4.16026201e+03, 2.20264658e+04])

In [103]:
# Diagonal matrix
np.diag([4,5,6])

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [104]:
np.random.rand(4)

np.random.rand(2,2,2)

np.random.rand(3,4)

array([[0.4841574 , 0.45395565, 0.66532262, 0.16460471],
       [0.97082983, 0.08361426, 0.27244281, 0.2483066 ],
       [0.40761893, 0.94464954, 0.48898503, 0.45499747]])

In [105]:
np.random.randn(2,3)

array([[ 0.31481046, -0.79621456, -0.44753045],
       [ 0.91316249,  0.13062608, -0.45175683]])

In [106]:
arr = np.random.randint(0,10,10)
arr

array([9, 4, 0, 5, 1, 3, 8, 6, 9, 1])

In [107]:
arr.reshape(2,5)

array([[9, 4, 0, 5, 1],
       [3, 8, 6, 9, 1]])

In [108]:
arr = np.random.randint(0,10,(4,3))
arr

array([[4, 1, 3],
       [5, 1, 8],
       [5, 1, 4],
       [9, 1, 6]])

In [109]:
arr.reshape(6,2)

array([[4, 1],
       [3, 5],
       [1, 8],
       [5, 1],
       [4, 9],
       [1, 6]])

In [110]:
arr = np.random.randint(0,100,(4,3))
print(arr)

print(arr.max())

# Index containing the max value
print(arr.argmax())

[[47 35 91]
 [77 17 48]
 [43 25 23]
 [30 79 70]]
91
2


In [111]:
arr = np.random.randint(0,100,(4,3))
print(arr)

print(arr.min())

# Index containing the max value
print(arr.argmin())

[[97 18 96]
 [20 82 28]
 [ 4 29 55]
 [44 83 37]]
4
6


In [112]:
arr.shape

(4, 3)

In [113]:
# Show dimension of the array
arr.ndim

2

In [114]:
arr.size

12

In [115]:
arr.dtype

dtype('int64')

In [116]:
arr = np.random.rand(4,3)
arr.dtype

dtype('float64')

In [117]:
# returns the size (in bytes) of each element of a NumPy array
arr.itemsize

8

In [118]:
arr2 = arr

print(arr.data)
print(arr2.data)

**Array Indexing**

In [119]:
sample_arr = np.random.randint(0,100,10)

sample_arr

array([92, 53, 85, 77,  6, 52, 69, 52,  0, 79])

In [120]:
sample_arr[3]

77

In [121]:
for data in sample_arr:
  print(data)

92
53
85
77
6
52
69
52
0
79


In [122]:
for i in range(len(sample_arr)):
  print(sample_arr[i])

92
53
85
77
6
52
69
52
0
79


In [123]:
print(sample_arr)
sample_arr[1:6]

[92 53 85 77  6 52 69 52  0 79]


array([53, 85, 77,  6, 52])

In [124]:
sample_arr[:5]

array([92, 53, 85, 77,  6])

In [125]:
sample_arr[5:]

array([52, 69, 52,  0, 79])

In [126]:
# arr = sample_arr[5:]

# arr[:3] = 100
# print(arr)

# sample_arr

In [127]:
arr = sample_arr.copy()

arr[:] = 1000

print(arr)
print(sample_arr)


[1000 1000 1000 1000 1000 1000 1000 1000 1000 1000]
[92 53 85 77  6 52 69 52  0 79]


In [130]:
arr2d = np.random.randint(0,100,(5,5))

In [132]:
print(arr2d)
arr2d[1][2]

[[63 92 24  5 27]
 [21 51 31 77 92]
 [89 81 17 96 71]
 [95 14 38 91 71]
 [ 0 20 25 99 20]]


31

In [134]:
arr2d[3,1]

14

**Array Selection**

In [135]:
arr2d[:2,1:]

array([[92, 24,  5, 27],
       [51, 31, 77, 92]])

In [137]:
arr2d[1:3,1:3]

array([[51, 31],
       [81, 17]])

In [143]:
arr = np.arange(0,11)
print(arr)

bool_arr = arr > 4
print(bool_arr)

arr[arr > 4]
arr[bool_arr]

[ 0  1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True  True]


array([ 5,  6,  7,  8,  9, 10])

**Array operations**

In [148]:
lst = [1,2,3]
lst + lst

[1, 2, 3, 1, 2, 3]

In [150]:
# NumPy has brodcasting ability

arr = np.arange(1,13)
print(arr)

arr + arr
# arr - arr
# arr * arr
# arr / arr

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [155]:
arr = np.arange(1,13).reshape(4,3)
arr2 = np.arange(1,13).reshape(4,3)

print(arr)
print("\n")
print(arr2)
print("\n")

arr * arr2

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]




array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

In [156]:
np.add(arr, arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [157]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162]])

In [159]:
np.max(arr)

12

In [160]:
np.exp(arr)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [161]:
np.sin(arr)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292]])