<a href="https://colab.research.google.com/github/fattahsamit/ml/blob/main/ML_Basics/NumPy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install numpy

In [4]:
import numpy as np

In [5]:
python_list = [1, 2, 3, 4, 5]

arr = np.array(python_list)
arr

array([1, 2, 3, 4, 5])

In [6]:
python_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

arr = np.array(python_list)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
arr = np.arange(0, 10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])

In [23]:
print(np.zeros(5))
print("\n")

np.zeros((4,3), dtype=int)

[0. 0. 0. 0. 0.]




array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.ones((4,3,5), dtype=int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [31]:
np.full((4,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [34]:
# Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
np.linspace(-1,1,5)

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [43]:
np.logspace(0,10,7, base=np.e)

# np.logspace(0,10,7)

# np.logspace(0,10,7, base=2)

array([1.00000000e+00, 5.29449005e+00, 2.80316249e+01, 1.48413159e+02,
       7.85771994e+02, 4.16026201e+03, 2.20264658e+04])

In [46]:
# Diagonal matrix
np.diag([4,5,6])

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])