<a href="https://colab.research.google.com/github/fattahsamit/ml/blob/main/ML_Basics/NumPy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
python_list = [1, 2, 3, 4, 5]

arr = np.array(python_list)
arr

array([1, 2, 3, 4, 5])

In [4]:
python_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

arr = np.array(python_list)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
arr = np.arange(0, 10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])

In [7]:
print(np.zeros(5))
print("\n")

np.zeros((4,3), dtype=int)

[0. 0. 0. 0. 0.]




array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.ones((4,3,5), dtype=int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [10]:
np.full((4,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [11]:
# Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.linspace(-1,1,5)

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [13]:
np.logspace(0,10,7, base=np.e)

# np.logspace(0,10,7)

# np.logspace(0,10,7, base=2)

array([1.00000000e+00, 5.29449005e+00, 2.80316249e+01, 1.48413159e+02,
       7.85771994e+02, 4.16026201e+03, 2.20264658e+04])

In [14]:
# Diagonal matrix
np.diag([4,5,6])

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [18]:
np.random.rand(4)

np.random.rand(2,2,2)

np.random.rand(3,4)

array([[0.69212389, 0.76604303, 0.39178293, 0.31845107],
       [0.56546592, 0.5337102 , 0.56618896, 0.36125533],
       [0.89029355, 0.14291156, 0.42463653, 0.14172483]])

In [19]:
np.random.randn(2,3)

array([[-1.54584527, -0.18696554,  1.12727607],
       [ 0.20136576, -1.85296269,  1.67988367]])

In [36]:
arr = np.random.randint(0,10,10)
arr

array([8, 3, 2, 4, 4, 3, 6, 2, 4, 6])

In [37]:
arr.reshape(2,5)

array([[8, 3, 2, 4, 4],
       [3, 6, 2, 4, 6]])

In [38]:
arr = np.random.randint(0,10,(4,3))
arr

array([[0, 4, 8],
       [8, 2, 0],
       [5, 9, 6],
       [9, 8, 5]])

In [39]:
arr.reshape(6,2)

array([[0, 4],
       [8, 8],
       [2, 0],
       [5, 9],
       [6, 9],
       [8, 5]])

In [51]:
arr = np.random.randint(0,100,(4,3))
print(arr)

print(arr.max())

# Index containing the max value
print(arr.argmax())

[[ 4 28 87]
 [31 53 79]
 [32 99  4]
 [26 77 64]]
99
7


In [52]:
arr = np.random.randint(0,100,(4,3))
print(arr)

print(arr.min())

# Index containing the max value
print(arr.argmin())

[[77 75 20]
 [ 9 62 58]
 [ 0  6 68]
 [13 96 25]]
0
6


In [53]:
arr.shape

(4, 3)

In [55]:
# Show dimension of the array
arr.ndim

2

In [56]:
arr.size

12

In [59]:
arr.dtype

dtype('int64')

In [60]:
arr = np.random.rand(4,3)
arr.dtype

dtype('float64')

In [63]:
# returns the size (in bytes) of each element of a NumPy array
arr.itemsize

8

In [64]:
arr2 = arr

print(arr.data)
print(arr2.data)